import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { NextResponse } from 'next/server'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const response = NextResponse.next()
  function setCookie(name: string ,value: string ,days: number) {
    var expires = "";
    if (days) {
        var date = new Date();
        date.setTime(date.getTime() + (days*24*60*60*1000));
        expires = "; expires=" + date.toUTCString();
    }
    document.cookie = name + "=" + (value || "")  + expires + "; path=/";
}
  const router = useRouter();
  const login = () => {
    setCookie("logged", 'true', 5)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

          <h2>index aqui</h2>
          <button onClick={login}>login</button>
          <button onClick={() => router.push("/home")}>home</button>
    </div>
  )
}

export default Home
